# Generated by Django 3.0.14 on 2022-05-01 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('IdComuna', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
    ]
