# Generated by Django 3.0.14 on 2022-05-01 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appEmpresa', '0001_initial'),
        ('appContacto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('IdAgenda', models.AutoField(primary_key=True, serialize=False)),
                ('Contacto_agenda', models.ForeignKey(db_column='Contacto', on_delete=django.db.models.deletion.CASCADE, to='appContacto.Contacto')),
                ('Empresa_agenda', models.ForeignKey(db_column='Empresa', on_delete=django.db.models.deletion.CASCADE, to='appEmpresa.Empresa')),
            ],
        ),
    ]
